# Generated by Django 3.2.13 on 2022-05-25 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alumnos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('matricula', models.CharField(max_length=50)),
                ('promedio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='profesores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numeroEmpleado', models.IntegerField()),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('horasClase', models.IntegerField()),
            ],
        ),
    ]
