# Generated by Django 3.2.13 on 2022-04-26 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='profesores',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('numeroEmpleado', models.IntegerField()),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('horasClase', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='matricula',
            field=models.CharField(max_length=50),
        ),
    ]
