# Generated by Django 3.2.13 on 2022-05-26 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restAPI', '0003_alter_alumnos_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='foto_perfil',
            field=models.CharField(max_length=1000),
        ),
    ]
