# Generated by Django 3.2.13 on 2022-05-26 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restAPI', '0004_alter_alumnos_foto_perfil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumnos',
            old_name='foto_perfil',
            new_name='fotoPerfilUrl',
        ),
    ]
