"""
Django settings for AWSAPIProject project.

Generated by 'django-admin startproject' using Django 3.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-3q9j&2(j%v3j)di0+vl5jts)#fh9-1x4)(_bxzea1ibi#zit9m'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['ec2-54-198-5-150.compute-1.amazonaws.com', '127.0.0.1', 'localhost']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'restAPI',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'AWSAPIProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'AWSAPIProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'projectDB',
        'USER': 'admin',
        'PASSWORD': 'adminpassword',
        'HOST': 'aws-project-database.ci2qf5x603fn.us-east-1.rds.amazonaws.com',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

APPEND_SLASH = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
STATIC_ROOT = os.path.join(BASE_DIR, "static/")

DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

AWS_PROFILE = 'default'
AWS_ACCESS_KEY_ID="ASIAX5W5OVHZNN6MG6FL"
AWS_SECRET_ACCESS_KEY='dSsEdXqsP5lvc3mPrTiLo7PKUdF6vNIFwF5YgrWV'
AWS_STORAGE_BUCKET_NAME='uadyawslabprojectbucket'
AWS_SESSION_TOKEN='FwoGZXIvYXdzENT//////////wEaDIW7uXZmEL6cZm4bMyLPAQw6z/fYdEuXICeKi3zGUAUpalLrbWwov0pZz0hpKpGkYwIhhopXJLLJr/4S1Man49vY/MEn6f5ApFNgTJUeD2qFAxNvVqVcEZq5/20V1ygjUpAOCziol9ZChLhbfl/8rqccjH7GuFDS3M/ed7wFFYEBTsLCQq5s3Vx6iJgd3uVvzdT/7hhKYilCSBNXrTWh0QcSFdiS+bUc1kAKAcOQSZTLk5sC4basHbmVmV4CeEmUHsiXQeIpF9sdT76wj84vwf7SYWkJP/NCmxDuSRYaQijnkL+UBjIt2GpPDvFxdAXZcIfw/cnT/eCyAoRv8+F2Tppf/8Jc5+7SuUgHMXynFy9YfQS6'
AWS_DEFAULT_REGION='us-east-1'
AWS_QUERYSTRING_AUTH = False
AWS_DEFAULT_ACL ='public-read'
